### ISSUE TITLE
implement requestIDs

### ISSUE THREAD

**Issue by lukastaegert** [FormidableLabs/mock-raf#1]
When using this really helpful mock library, I came about an issue where I wanted to check if animation frames were properly cancelled by our app. Since cancelling currently means for mock-raf that ALL callbacks are removed, not only the ones specified via an ID, this was not possible.

I have implemented a possible change, along with a simple mocha test, that would implement this functionality without breaking backwards compatibility (hopefully). I will make a pull request shortly.

**Comment by ryan-roemer** [comment]
@alexlande -- Any thoughts?

**Comment by alexlande** [comment]
Sorry @lukastaegert, I wasn't watching this repo for some reason. Thanks for the heads up @ryan-roemer. I'll review your PR now, sounds like a great feature!

**Comment by alexlande** [comment]
Resolved by #6
