### ISSUE TITLE
useMockedRAF

### ISSUE THREAD

**Issue by appsforartists** [FormidableLabs/mock-raf#7]
The README recommends mocking `window.requestAnimationFrame`, which is a scary proposition, since it would be easy to forget to put it back to the native implementation (hence, breaking encapsulation, and perhaps unrelated tests).

I [took a stab](https://github.com/appsforartists/mock-raf/commits/wrapper) at making a wrapper to make this automatic:

```javascript
describe('my test',
  useMockedRAF(
    (mockRAF) => {
      it('does some stuff',
```

`mocha` tests aren't synchronous, so I had to wrap the `sinon.stub` call in `before`, but then `sinon` was complaining that I was trying to wrap something that was already wrapped.

There's clearly some scheduling sorcery going on in these testing frameworks that I'm unfamiliar with, but I'd love to see someone who knows them better than I do (or has time to dissect them) take this over.  😃

**Comment by ryan-roemer** [comment]
This library doesn't actually mutate `window.requestAnimationFrame` and it is just the use case that we're solving that _does_ want to mutate it.

There's no real danger of stubbing that in Mocha tests since there are many, many ways to get guaranteed un-stubbing, e.g.:

- Stub in `before|beforeEach`, unstub in `after|afterEach`
- Create a `sinon.sandbox` in `before|beforeEach`, use `sandbox` to stub whatever, restore `sandbox` in `after|afterEach`

All with very conventional uses of Sinon and Mocha.

**Comment by ryan-roemer** [comment]
Also in your example, you're not unstubbing correctly with this line: https://github.com/appsforartists/mock-raf/commit/06af9a55b516e8daf8f0220389437b15e1d307f1#diff-e90b58bdf4211c7424b9fe28d05202c4R20

```js
window.requestAnimationFrame = originalRAF;
```

The standard:

```js
window.requestAnimationFrame.restore();
```

is what you should use instead.

**Comment by appsforartists** [comment]
Thanks.  As you may have noticed, I'm fairly new to `sinon`.  I've pushed an update to my proposal, but I'm still seeing 

```
TypeError: Attempted to wrap requestAnimationFrame which is already wrapped
```

**Comment by ryan-roemer** [comment]
@appsforartists -- The error comes from not using `sinon` exactly correctly. I don't have time to dive into your wrapper, but I think it's out of scope for this project -- which is _just_ the mock implementation and _not_ the tests, etc.

You've added `sinon` and other dependencies which makes this library more heavyweight. And, it's not vanilla ES5 which this library is.

However -- your wrapper project may be very useful once you work out the kinks for other users that don't want to set things up manually. We encourage you to do a separate project with just the wrapper abstraction!

**Comment by appsforartists** [comment]
I forgot to wrap the return value in a closure; that fixed the issue.

`sinon` should be in `peerDependencies`, so it doesn't add to download size, and it would be trivial to replace the `const`s with `var`s if you prefer.  I can certainly host this in a separate repo - I just see value in making the common case easy and error free for all `mock-raf` users, so I wanted to offer it here first.  😃
